version: "3"

services:
  user:
    build: ./UserService .
    ports:
    - "8080:8080"
    networks:
      - local
  trip:
    build: ./TripService .
    ports:
      - "8082:8082"
    networks:
      - local
  pricing:
    build: ./PricingService .
    ports:
      - "8083:8083"
    networks:
      - local
  match:
    build: ./MatchService .
    ports:
      - "8081:8081"
    networks:
      - local
networks:

  local:
    driver: bridge